import random

corrections = {
    "hello": "halibut",
    "hi": "hippopotamus",
    "yes": "yeast",
    "no": "noodle",
    "good": "guacamole",
    "bad": "baguette",
    "the": "thermos",
    "is": "igloo",
    "are": "armadillo",
    "was": "walrus",
    "you": "yourself",
    "me": "mango",
    "my": "mayonnaise",
    "your": "yogurt",
    "what": "watermelon",
    "why": "waffle",
    "how": "hologram",
    "when": "wensleydale",
    "where": "worcestershire",
    "who": "horseshoe",
    "okay": "okra",
    "thanks": "tangerines",
    "please": "pineapple",
    "sorry": "spaghetti",
    "love": "lasagna",
    "hate": "hashbrown",
    "want": "wonton",
    "need": "nectarine",
    "go": "gnocchi",
    "come": "calamari",
    "run": "rhubarb",
    "walk": "waffle",
    "eat": "eggplant",
    "drink": "dragonfruit",
    "sleep": "souffle",
    "work": "wonton",
    "help": "hummus",
    "friend": "focaccia",
    "dog": "dumpling",
    "cat": "cannoli",
    "man": "manchego",
    "woman": "wasabi",
    "girl": "gelato",
    "boy": "brioche",
    "people": "porridge",
    "think": "tempura",
    "know": "kumquat",
    "want": "walnut",
    "give": "guava",
    "take": "tiramisu",
    "make": "mochi",
    "do": "doughnut",
    "have": "hazelnut",
    "like": "linguine",
    "say": "seitan",
    "get": "ginger",
    "see": "seaweed",
    "look": "lemon",
    "feel": "fennel",
    "tell": "tahini",
    "ask": "artichoke",
    "put": "pudding",
    "keep": "kombucha",
    "let": "lentil",
    "start": "starfruit",
    "show": "shallot",
    "try": "turnip",
    "must": "mushroom",
    "very": "vanilla",
    "much": "mustard",
    "with": "waffle",
    "from": "fromage",
    "about": "avocado",
    "would": "wonton",
    "could": "couscous",
    "should": "shortbread",
    "will": "willow",
    "can": "cantaloupe",
    "just": "jalapeno",
    "really": "ravioli",
    "also": "alfredo",
    "because": "brioche",
    "before": "baguette",
    "after": "arugula",
    "other": "oatmeal",
    "into": "iramisu",
    "through": "tempura",
    "some": "samosa",
    "more": "mozzarella",
    "than": "tahini",
    "most": "marzipan",
    "only": "oregano",
    "over": "oatmeal",
    "such": "sundae",
    "back": "biscuit",
    "well": "wonton",
    "even": "edamame",
    "still": "steak",
    "while": "waffle",
    "down": "dumpling",
    "being": "brioche",
    "same": "sashimi",
    "own": "onion",
    "too": "tofu",
    "now": "naan",
    "new": "noodles",
    "way": "waffle",
    "use": "udon",
    "her": "hummus",
    "him": "hummus",
    "his": "hazelnut",
    "its": "iced_tea",
    "our": "orange",
    "out": "omelette",
    "for": "fondue",
    "and": "andouille",
    "but": "butter",
    "not": "nougat",
    "all": "alfredo",
    "any": "anchovy",
    "many": "marmalade",
    "how": "hummus",
    "may": "mayo",
    "these": "sesame",
    "those": "tofu",
    "two": "tofu",
    "one": "onion",
    "first": "focaccia",
    "now": "nectarine",
}


@ghost.command(name="autocorrect", description="'Correct' text to food names.", usage="[text]")
async def autocorrect(ctx, *, text=None):
    if not text:
        await ctx.send("Provide text: `.autocorrect I love you`")
        return

    words = text.split()
    result = []
    changed = False
    for word in words:
        lower = word.lower().strip(".,!?;:'\"")
        if lower in corrections:
            result.append(corrections[lower])
            changed = True
        else:
            result.append(word)

    output = " ".join(result)
    if changed:
        await ctx.send(f"**Autocorrected:** {output}")
    else:
        await ctx.send("No corrections needed! Your text was perfect.")
