import random

fortunes = [
    "A beautiful, smart, and loving person will come into your life.",
    "A dubious friend may be an enemy in camouflage.",
    "A faithful friend is a strong defense.",
    "A fresh start will put you on your way.",
    "A golden egg of opportunity falls into your lap this month.",
    "A good time to finish up old tasks.",
    "A lifetime of happiness lies ahead of you.",
    "A light heart carries you through all the hard times.",
    "A new perspective will come with the new year.",
    "A pleasant letter from someone distant is in your future.",
    "A small donation is the most thoughtful gift.",
    "A smooth sea never made a skilled sailor.",
    "A stranger will soon become a very important friend.",
    "A truly rich life is one full of love.",
    "Adventure can be real happiness.",
    "All the effort you are putting into your career will pay off.",
    "An important person will offer you support.",
    "Believe in yourself and others will too.",
    "Changes in your life today will lead to greater contentment.",
    "Courage is not the absence of fear; it is acting in spite of it.",
    "Disregard the last fortune and focus on this one.",
    "Do not make extra work for yourself.",
    "During the next two months, you will receive good news.",
    "Every day in your life is a special occasion.",
    "Failure is the chance to do better next time.",
    "Fortune favors the brave.",
    "From small beginnings come great things.",
    "Good news will come to you by mail.",
    "Happiness begins with facing life with a smile and a wink.",
    "Hard work pays off in the future, however laziness pays off now.",
    "Have you tried turning it off and on again?",
    "He who laughs at himself never runs out of things to laugh at.",
    "Help! You need someone.",
    "Hold tight to your dreams.",
    "How you look depends on where you go.",
    "If you continually give, you will continually have.",
    "If you don't expect too much from yourself, you will be surprised.",
    "If you keep your feet on the ground, you will bump your head.",
    "It is always the simple that produces the marvelous.",
    "It is better to be a failure at something you love than a success at something you hate.",
    "It is worth checking to see if you are holding on to something that is not worth holding on to.",
    "Let the decisions you make reflect the hopes and not the fears.",
    "Nothing is impossible to a willing heart.",
    "Observe your surroundings. They may hold the answer.",
    "Once in a while, you really need to take a break and be grateful for what you have.",
    "Others admire your independent spirit.",
    "Sail swiftly on the waters of life.",
    "The best prediction of the future is to create it.",
    "The one that will be first will be last.",
]


@ghost.command(name="fortune", description="Get your fortune told.", usage="")
async def fortune(ctx):
    f = random.choice(fortunes)
    await ctx.send(f"**Fortune:** {f}")
